config/routes.rb
Rails.application.routes.draw do
 root 'tasks#index'
 resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
    if params[:method] == 'delete'
      @task.destroy
      redirect_to tasks_path
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params 
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_area :details %>

   <%= f.label :completed %>
  <%= f.text_area :completed %>

  <%= f.submit 'Update Task', class: 'btn btn-primary' %>
<% end %>

app/views/tasks/index.html.erb
<h1>Task List</h1>

<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task) %></li>
  <% end %>
</ul>

<%= link_to 'Create a new task', new_task_path%>

app/views/tasks/new.html.erb
<!-- app/views/tasks/new.html.erb -->
<h1>Create new task</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

   <%= f.label :completed %>
  <%= f.text_field :completed %>

 <%= f.submit 'Create Task', class: 'btn btn-primary' %>
<% end %>

app/views/tasks/show.html.erb
<h1>Task Info</h1>

<p>Title: <%= @task.title %></p> 
<p>Details: <%= @task.details %></p> 
<p>Completed: <%= @task.completed %></p> 


<p>
  <%= link_to "Back to index", tasks_path %>
</p>

<p>
  <%= link_to "Edit task", edit_task_path %>
</p>

<p>
<%= link_to "Remove Task", method: :delete %>
</p>